### ISSUE TITLE
more detail request

### ISSUE THREAD

**Issue by aliuygur** [vegasbrianc/docker-traefik-prometheus#1]
Hello, thanks a lot.

Now, I am testing this https://github.com/vegasbrianc/prometheus this worked perfectly, but i can't monitor traefik metrics.

I have started traefik with the docker-compose.yml file, then import https://grafana.com/dashboards/4475 but i can't see any data on this dashboard.

I have few questions

- Should I modify prometheus/prometheus.yml file?
- which dashboard should I import from grafana dashboards for traefik?

**Comment by vegasbrianc** [comment]
HI @alioygur I was just updating this yesterday. I will have a new updated dashboard this week. Can you login to Prometheus 0.0.0.0:9090 and check to see if the traefik metrics are at the bottom of the list? 

Second, can you go to the Prometheus Status Menu -> Targets and let me know if you see that Traefik is online?

**Comment by aliuygur** [comment]
@vegasbrianc Hello,

> Can you login to Prometheus 0.0.0.0:9090 and check to see if the traefik metrics are at the bottom of the list?

No

> Second, can you go to the Prometheus Status Menu -> Targets and let me know if you see that Traefik is online?

No :(

I will say again, should i edit prometheus/prometheus.yml file for traefik metrics?

this is my prometheus.yml file. (I haven't modified this)

```
# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
         - targets: ['localhost:9090']


  - job_name: 'cadvisor'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

#     static_configs:
#          - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100
    
#     static_configs:
#          - targets: ['node-exporter:9100']
```
